// Copyright 2025 Catalogic Software, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cloudcasa

import (
	"context"
	"time"

	cloudcasa "terraform-provider-cloudcasa/cloudcasa/client"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &resourceKubecluster{}
	_ resource.ResourceWithConfigure   = &resourceKubecluster{}
	_ resource.ResourceWithImportState = &resourceKubecluster{}
)

func NewResourceKubecluster() resource.Resource {
	return &resourceKubecluster{}
}

type resourceKubecluster struct {
	Client *cloudcasa.Client
}

// kubeclusterResourceModel maps the resource schema data.
type kubeclusterResourceModel struct {
	Name             types.String `tfsdk:"name"`
	Id               types.String `tfsdk:"id"`
	Auto_install     types.Bool   `tfsdk:"auto_install"`
	Updated          types.String `tfsdk:"updated"`
	Created          types.String `tfsdk:"created"`
	Etag             types.String `tfsdk:"etag"`
	Status           types.Map    `tfsdk:"status"`
	Links            types.Map    `tfsdk:"links"`
	Agent_url        types.String `tfsdk:"agent_url"`
	UserObjectstore  types.String `tfsdk:"objectstore_id"`
}

// Metadata returns the data source type name.
func (r *resourceKubecluster) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_kubecluster"
}

// Schema defines the schema for the resource.
func (r *resourceKubecluster) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "CloudCasa kubecluster configuration",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Description: "CloudCasa resource ID",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "CloudCasa resource name",
			},
			"auto_install": schema.BoolAttribute{
				Optional: true,
				Description: "Automatically install the CloudCasa agent and register the current kubernetes cluster. Uses KUBECONFIG environment variable for cluster context." +
					"Set to false to manage or reference a CloudCasa kubecluster resource without installing the agent on a cluster.",
			},
			"updated": schema.StringAttribute{
				Computed:    true,
				Description: "Last update time of the CloudCasa resource",
			},
			"created": schema.StringAttribute{
				Computed:    true,
				Description: "Creation time of the CloudCasa resource",
			},
			"etag": schema.StringAttribute{
				Computed:    true,
				Description: "Etag generated by CloudCasa, used for updating resources in place",
			},
			"status": schema.MapAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: "Cluster status from CloudCasa",
			},
			"links": schema.MapAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: "Related resources from CloudCasa",
			},
			"agent_url": schema.StringAttribute{
				Computed:    true,
				Description: "CloudCasa Kubeagent installation manifest URL",
			},
			"objectstore_id": schema.StringAttribute{
				Optional:    true,
				Description: "ID of the CloudCasa objectstore to use for backups",
			},
		},
	}
}

// Configure adds the provider configured client to the data source.
func (r *resourceKubecluster) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	r.Client = req.ProviderData.(*cloudcasa.Client)
}

// Create creates the resource and sets the initial Terraform state.
func (r *resourceKubecluster) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	// Retrieve values from plan
	var plan kubeclusterResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Define kubecluster object
	reqBody := map[string]interface{}{
		"name": plan.Name.ValueString(),
	}

	// Add backup_provider.user_objectstore if specified
	if !plan.UserObjectstore.IsNull() {
		reqBody["backup_provider"] = map[string]string{
			"user_objectstore": plan.UserObjectstore.ValueString(),
		}
	}

	// Create kubecluster in cloudcasa
	createResp, err := r.Client.CreateKubecluster(reqBody)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Creating Kubecluster",
			err.Error(),
		)
		return
	}

	// Set fields in plan
	plan.Id = types.StringValue(createResp.Id)
	plan.Name = types.StringValue(createResp.Name)
	plan.Created = types.StringValue(createResp.Created)
	plan.Updated = types.StringValue(createResp.Updated)
	plan.Etag = types.StringValue(createResp.Etag)

	// if auto_install is false return now. Otherwise proceed with agent installation
	if !plan.Auto_install.ValueBool() {
		plan.Agent_url = types.StringNull()
		plan.Links = types.MapNull(types.StringType)
		plan.Status = types.MapNull(types.StringType)
		diags = resp.State.Set(ctx, plan)
		return
	}

	var kubeclusterStatus cloudcasa.KubeclusterStatus

	// wait 1m for agent URL
	for i := 1; i < 12; i++ {
		getKubeclusterResp, err := r.Client.GetKubecluster(createResp.Id)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error checking Kubecluster status after creation",
				err.Error(),
			)
			return
		}
		kubeclusterStatus = getKubeclusterResp.Status
		if len(kubeclusterStatus.Agent_url) > 0 {
			break
		}
		time.Sleep(5 * time.Second)
	}

	// Check that Agent URL was fetched successfully
	if len(kubeclusterStatus.Agent_url) == 0 {
		resp.Diagnostics.AddError(
			"Failed to get Agent URL for kubecluster",
			"Timed out waiting for Agent URL: "+err.Error(),
		)
		return
	}

	// Set agent url from response
	plan.Agent_url = types.StringValue(kubeclusterStatus.Agent_url)

	// Apply agent spec and wait for ACTIVE
	err = r.Client.ApplyKubeagent(createResp.Id, kubeclusterStatus.Agent_url)
	if err != nil {
		resp.Diagnostics.AddError(
			"CloudCasa agent installation failed",
			err.Error(),
		)
	}

	// Save state before returning
	plan.Links = types.MapNull(types.StringType)
	plan.Status = types.MapNull(types.StringType)

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Read refreshes the Terraform state with the latest data.
// and apply the agent with current kubeconfig if not active.
func (r *resourceKubecluster) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Get current state
	var state kubeclusterResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get refreshed Kubecluster from CloudCasa
	getKubeclusterResp, err := r.Client.GetKubecluster(state.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error getting Kubecluster from CloudCasa",
			"Could not read Kubecluster with ID "+state.Id.ValueString()+" :"+err.Error(),
		)
		return
	}

	// Check kubecluster status
	// if auto_install is true, we should apply kubeagent spec if status is bad
	if getKubeclusterResp.Status.State != "ACTIVE" {
		err = r.Client.ApplyKubeagent(getKubeclusterResp.Id, getKubeclusterResp.Status.Agent_url)
		if err != nil {
			resp.Diagnostics.AddError(
				"Error installing Kubeagent on existing cluster",
				err.Error(),
			)
			return
		}
	}

	// Overwrite values with refreshed state
	// Set fields in plan
	state.Id = types.StringValue(getKubeclusterResp.Id)
	state.Name = types.StringValue(getKubeclusterResp.Name)
	state.Created = types.StringValue(getKubeclusterResp.Created)
	state.Updated = types.StringValue(getKubeclusterResp.Updated)
	state.Etag = types.StringValue(getKubeclusterResp.Etag)
	
	// Handle user_objectstore if present in the response
	if getKubeclusterResp.BackupProvider.UserObjectstore != "" {
		state.UserObjectstore = types.StringValue(getKubeclusterResp.BackupProvider.UserObjectstore)
	} else {
		state.UserObjectstore = types.StringNull()
	}

	// Set refreshed state
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Update updates the resource and sets the updated Terraform state on success.
func (r *resourceKubecluster) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Retrieve values from plan
	var plan kubeclusterResourceModel
	diags := req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Get current state
	var state kubeclusterResourceModel
	diags = req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Define update body
	reqBody := map[string]interface{}{
		"name": plan.Name.ValueString(),
	}

	// Add backup_provider.user_objectstore if specified
	if !plan.UserObjectstore.IsNull() {
		reqBody["backup_provider"] = map[string]string{
			"user_objectstore": plan.UserObjectstore.ValueString(),
		}
	}

	// Update kubecluster in cloudcasa
	kubeclusterId := state.Id.ValueString()
	updateResp, err := r.Client.UpdateKubecluster(kubeclusterId, reqBody, state.Etag.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Updating CloudCasa Kubecluster",
			"Could not update CloudCasa kubecluster ID "+kubeclusterId+": "+err.Error(),
		)
		return
	}

	// Update state with refreshed values
	plan.Id = types.StringValue(updateResp.Id)
	plan.Name = types.StringValue(updateResp.Name)
	plan.Updated = types.StringValue(updateResp.Updated)
	plan.Created = types.StringValue(updateResp.Created)
	plan.Etag = types.StringValue(updateResp.Etag)
	
	// Check that Agent URL was fetched successfully
	kubeclusterStatus := updateResp.Status
	if len(kubeclusterStatus.Agent_url) == 0 {
		plan.Agent_url = types.StringValue("")
	} else {
		plan.Agent_url = types.StringValue(kubeclusterStatus.Agent_url)
	}
	
	// Handle user_objectstore from response
	if updateResp.BackupProvider.UserObjectstore != "" {
		plan.UserObjectstore = types.StringValue(updateResp.BackupProvider.UserObjectstore)
	} else {
		plan.UserObjectstore = types.StringNull()
	}

	// Save state before returning
	plan.Links = types.MapNull(types.StringType)
	plan.Status = types.MapNull(types.StringType)

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// Delete deletes the resource and removes the Terraform state on success.
func (r *resourceKubecluster) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// Retrieve values from state
	var state kubeclusterResourceModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.Client.DeleteKubecluster(state.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Deleting Kubecluster resource",
			err.Error(),
		)
		return
	}
}

func (r *resourceKubecluster) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Retrieve import ID and save to id attribute
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
